import com.eignex.kbuild.EignexCliExtension
import com.eignex.kbuild.KBUILD_JVM_TOOLCHAIN
import com.eignex.kbuild.applyKbuildCommonDependencies
import java.security.MessageDigest
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.plugin.mpp.Executable
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.NativeBuildType
import org.jetbrains.kotlin.gradle.targets.jvm.KotlinJvmTarget
import org.jetbrains.kotlin.konan.target.HostManager

plugins {
    kotlin("multiplatform")
    id("org.jetbrains.kotlinx.kover")
}

apply(plugin = "com.eignex.lint")

group = "com.eignex"
version = findProperty("ciVersion") as String? ?: "SNAPSHOT"

repositories { mavenCentral() }

val eignexCli = extensions.create<EignexCliExtension>("eignexCli")

kotlin {
    jvmToolchain(KBUILD_JVM_TOOLCHAIN)

    // Declare targets in your build.gradle.kts:
    //   jvm()
    //   linuxX64(); macosX64(); macosArm64()
    // The executable conventions below apply to whatever targets exist.

    applyKbuildCommonDependencies(project)
}

// --version build identity: generate an `internal object BuildInfo` into commonMain (so it's
// shared by every target — JVM and native) from the configured/project version, instead of
// each CLI hand-maintaining a constant that drifts from the real version. Generated under
// build/, so it's outside the detekt/checkKdoc `src` scan; it's `internal`, so dokka (which
// documents public API only) ignores it too — no lint to fight on generated code.
val generatedBuildInfoDir = layout.buildDirectory.dir("generated/eignexCliBuildInfo/kotlin")
// Capture project coordinates as plain Strings at configuration time (CC-safe defaults).
val projectVersion = version.toString()
val projectName = name
val projectGroup = group.toString()

val generateCliBuildInfo = tasks.register("generateCliBuildInfo") {
    description = "Generates the BuildInfo object (NAME/ID/VERSION) the CLI reports via --version."
    val outDir = generatedBuildInfoDir
    // Lazy: eignexCli is configured by the consumer after this plugin applies, so read it
    // through providers resolved at execution time. orElse supplies the project-derived default.
    val versionValue = eignexCli.version.orElse(projectVersion)
    val nameValue = eignexCli.appName.orElse(projectName)
    val idValue = eignexCli.appId.orElse(projectGroup)
    val packageValue = eignexCli.buildInfoPackage
        .orElse(eignexCli.mainClass.map { it.substringBeforeLast('.') })
        .orElse(projectGroup)
    inputs.property("version", versionValue)
    inputs.property("name", nameValue)
    inputs.property("id", idValue)
    inputs.property("package", packageValue)
    outputs.dir(outDir)
    doLast {
        fun esc(s: String) = s.replace("\\", "\\\\").replace("\"", "\\\"")
        val pkg = packageValue.get()
        val file = outDir.get().asFile.resolve(pkg.replace('.', '/') + "/BuildInfo.kt")
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("package $pkg")
                appendLine()
                appendLine("/** Build identity reported by the `--version` flag. Generated by com.eignex.cli; do not edit. */")
                appendLine("internal object BuildInfo {")
                appendLine("    /** Human-facing application name. */")
                appendLine("    const val NAME: String = \"${esc(nameValue.get())}\"")
                appendLine()
                appendLine("    /** Reverse-DNS application id. */")
                appendLine("    const val ID: String = \"${esc(idValue.get())}\"")
                appendLine()
                appendLine("    /** Project version string. */")
                appendLine("    const val VERSION: String = \"${esc(versionValue.get())}\"")
                appendLine()
                appendLine("    /** Single line for `--version` output, in `name version` form. */")
                appendLine("    fun versionLine(): String = \"\$NAME \$VERSION\"")
                appendLine("}")
            },
        )
    }
}

// srcDir(taskProvider) both adds the generated dir and makes compilation depend on the task,
// across every target via commonMain — same wiring as the root build's KbuildVersion source.
kotlin.sourceSets.named("commonMain") {
    kotlin.srcDir(generateCliBuildInfo)
}

// Eager all {}, not configureEach: the binaries DSL applies the distribution plugin,
// which calls afterEvaluate — forbidden inside lazy configuration actions.
kotlin.targets.withType<KotlinJvmTarget>().all {
    @OptIn(ExperimentalKotlinGradlePluginApi::class)
    binaries {
        executable {
            mainClass.set(eignexCli.mainClass)
        }
    }
}

// Everything below reads consumer configuration — the eignexCli extension and the target set —
// that only exists once the consumer's script has run.
afterEvaluate {
    // entryPoint is a plain var on the binary, not a lazy property, so the extension has to be
    // read eagerly here rather than wired through a provider.
    kotlin.targets.withType<KotlinNativeTarget>().configureEach {
        binaries.executable {
            eignexCli.entryPoint.orNull?.let { entryPoint = it }
        }
    }

    // Release packaging: collect renamed, stripped native executables and the JVM dist zip
    // into build/release-assets/, ready to upload as GitHub release assets.
    val baseName = project.name
    val assetVersion = version.toString()
    val assetsDir = layout.buildDirectory.dir("release-assets")

    // Only host-linkable targets: macOS binaries cannot be cross-linked from Linux and vice versa.
    val hostManager = HostManager()
    val nativeExecutables = kotlin.targets.withType<KotlinNativeTarget>()
        .filter { hostManager.isEnabled(it.konanTarget) }
        .flatMap { it.binaries.filterIsInstance<Executable>() }
        .filter { it.buildType == NativeBuildType.RELEASE }
    val jvmDistZip = tasks.findByName("jvmDistZip") as Zip?

    tasks.register("releaseAssets") {
        group = "distribution"
        description = "Collects stripped native executables and the JVM dist zip into build/release-assets."
        nativeExecutables.forEach { dependsOn(it.linkTaskProvider) }
        jvmDistZip?.let { dependsOn(it) }

        val nativeAssets = nativeExecutables.map { binary ->
            // linux_x64 -> linux-x64, mingw_x64 -> windows-x64
            val osArch = binary.target.konanTarget.name.replace("mingw", "windows").replace('_', '-')
            binary.outputFile to "$baseName-$assetVersion-$osArch"
        }
        val jvmZip = jvmDistZip?.archiveFile
        // macOS needs -x (non-global symbols only): a full strip fails on linked Mach-O executables.
        val stripCommand = if (HostManager.hostIsMac) listOf("strip", "-x") else listOf("strip")

        doLast {
            val dir = assetsDir.get().asFile
            dir.deleteRecursively()
            dir.mkdirs()
            val assets = mutableListOf<File>()
            for ((outputFile, assetName) in nativeAssets) {
                val asset = outputFile.copyTo(dir.resolve(assetName))
                asset.setExecutable(true)
                // Best effort: keep the unstripped binary if strip is unavailable.
                // Discard output: an unread pipe fills up and deadlocks waitFor.
                runCatching {
                    ProcessBuilder(stripCommand + asset.absolutePath)
                        .redirectOutput(ProcessBuilder.Redirect.DISCARD)
                        .redirectError(ProcessBuilder.Redirect.DISCARD)
                        .start()
                        .waitFor()
                }
                assets += asset
            }
            jvmZip?.let { assets += it.get().asFile.copyTo(dir.resolve("$baseName-$assetVersion-jvm.zip")) }
            val digest = MessageDigest.getInstance("SHA-256")
            dir.resolve("SHA256SUMS").writeText(
                assets.joinToString("") { asset ->
                    val sum = digest.digest(asset.readBytes()).joinToString("") { "%02x".format(it) }
                    "$sum  ${asset.name}\n"
                }
            )
        }
    }
}
