import com.eignex.kbuild.EignexCliExtension
import com.eignex.kbuild.applyKbuildCommonDependencies
import com.eignex.kbuild.getOrCreateEignexBuildExtension
import java.security.MessageDigest
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.plugin.mpp.Executable
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.NativeBuildType
import org.jetbrains.kotlin.gradle.targets.jvm.KotlinJvmTarget
import org.jetbrains.kotlin.konan.target.HostManager

plugins {
    kotlin("multiplatform")
    id("org.jetbrains.kotlinx.kover")
}

val eignexBuild = project.getOrCreateEignexBuildExtension()

apply(plugin = "com.eignex.lint")

version = findProperty("ciVersion") as String? ?: "SNAPSHOT"

val eignexCli = extensions.create<EignexCliExtension>("eignexCli")
eignexCli.releaseAssetsEnabled.convention(true)
eignexCli.releaseAssetPrefix.convention(name)
eignexCli.releaseAssetsDirectory.convention("build/release-assets")
eignexCli.stripReleaseBinaries.convention(true)

kotlin {
    // Declare targets in your build.gradle.kts:
    //   jvm()
    //   linuxX64(); macosX64(); macosArm64()
    // The executable conventions below apply to whatever targets exist.

    applyKbuildCommonDependencies(project, eignexBuild)
}

// --version build identity: an `internal object BuildInfo` generated into commonMain, so every
// target shares it and no CLI hand-maintains a constant that drifts. It lands under build/ and
// is internal, so neither the detekt/checkKdoc `src` scan nor dokka sees it.
val generatedBuildInfoDir = layout.buildDirectory.dir("generated/eignexCliBuildInfo/kotlin")
// Plain Strings captured at configuration time (CC-safe defaults).
val projectVersion = providers.provider { version.toString() }
val projectName = name
val projectGroup = providers.provider {
    group.toString().takeIf { it.isNotBlank() } ?: eignexBuild.defaultGroup.get()
}

val generateCliBuildInfo = tasks.register("generateCliBuildInfo") {
    description = "Generates the BuildInfo object (NAME/ID/VERSION) the CLI reports via --version."
    val outDir = generatedBuildInfoDir
    // Lazy: the consumer configures eignexCli after this plugin applies, so resolve at
    // execution time, with orElse supplying the project-derived default.
    val versionValue = eignexCli.version.orElse(projectVersion)
    val nameValue = eignexCli.appName.orElse(projectName)
    val idValue = eignexCli.appId.orElse(projectGroup)
    val packageValue = eignexCli.buildInfoPackage
        .orElse(eignexCli.mainClass.map { it.substringBeforeLast('.') })
        .orElse(projectGroup)
    inputs.property("version", versionValue)
    inputs.property("name", nameValue)
    inputs.property("id", idValue)
    inputs.property("package", packageValue)
    outputs.dir(outDir)
    doLast {
        fun esc(s: String) = s.replace("\\", "\\\\").replace("\"", "\\\"")
        val pkg = packageValue.get()
        val file = outDir.get().asFile.resolve(pkg.replace('.', '/') + "/BuildInfo.kt")
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("package $pkg")
                appendLine()
                appendLine("/** Build identity reported by the `--version` flag. Generated by com.eignex.cli; do not edit. */")
                appendLine("internal object BuildInfo {")
                appendLine("    /** Human-facing application name. */")
                appendLine("    const val NAME: String = \"${esc(nameValue.get())}\"")
                appendLine()
                appendLine("    /** Reverse-DNS application id. */")
                appendLine("    const val ID: String = \"${esc(idValue.get())}\"")
                appendLine()
                appendLine("    /** Project version string. */")
                appendLine("    const val VERSION: String = \"${esc(versionValue.get())}\"")
                appendLine()
                appendLine("    /** Single line for `--version` output, in `name version` form. */")
                appendLine("    fun versionLine(): String = \"\$NAME \$VERSION\"")
                appendLine("}")
            },
        )
    }
}

// srcDir(taskProvider) adds the dir and makes every target's compilation depend on the task.
kotlin.sourceSets.named("commonMain") {
    kotlin.srcDir(generateCliBuildInfo)
}

// Eager all {}, not configureEach: the binaries DSL applies the distribution plugin,
// which calls afterEvaluate, forbidden inside lazy configuration actions.
kotlin.targets.withType<KotlinJvmTarget>().all {
    @OptIn(ExperimentalKotlinGradlePluginApi::class)
    binaries {
        executable {
            mainClass.set(eignexCli.mainClass)
        }
    }
}

// Everything below reads consumer configuration that exists only after their script has run.
afterEvaluate {
    if (eignexBuild.useMavenCentral.get()) repositories.mavenCentral()
    kotlin {
        jvmToolchain(eignexBuild.jvmToolchain.get())
    }
    if (!eignexBuild.lintEnabled.get()) {
        tasks.matching { it.name.startsWith("detekt") || it.name == "checkKdoc" }.configureEach {
            enabled = false
        }
    }
    if (!eignexBuild.koverEnabled.get()) {
        tasks.matching { it.name.startsWith("kover") }.configureEach { enabled = false }
    }
    if (!eignexCli.releaseAssetsEnabled.get()) return@afterEvaluate

    // entryPoint is a plain var on the binary, not a property, so it cannot take a provider.
    kotlin.targets.withType<KotlinNativeTarget>().configureEach {
        binaries.executable {
            eignexCli.entryPoint.orNull?.let { entryPoint = it }
        }
    }

    // Release packaging: renamed, stripped native executables plus the JVM dist zip, collected
    // into build/release-assets/ for upload to a GitHub release.
    val baseName = eignexCli.releaseAssetPrefix.get()
    val assetVersion = version.toString()
    val assetsDir = layout.projectDirectory.dir(eignexCli.releaseAssetsDirectory.get())

    // Only host-linkable targets: macOS binaries cannot be cross-linked from Linux and vice versa.
    val hostManager = HostManager()
    val nativeExecutables = kotlin.targets.withType<KotlinNativeTarget>()
        .filter { hostManager.isEnabled(it.konanTarget) }
        .flatMap { it.binaries.filterIsInstance<Executable>() }
        .filter { it.buildType == NativeBuildType.RELEASE }
    val jvmDistZip = tasks.findByName("jvmDistZip") as Zip?

    tasks.register("releaseAssets") {
        group = "distribution"
        description = "Collects stripped native executables and the JVM dist zip into build/release-assets."
        nativeExecutables.forEach { dependsOn(it.linkTaskProvider) }
        jvmDistZip?.let { dependsOn(it) }

        val nativeAssets = nativeExecutables.map { binary ->
            // linux_x64 -> linux-x64, mingw_x64 -> windows-x64
            val osArch = binary.target.konanTarget.name.replace("mingw", "windows").replace('_', '-')
            binary.outputFile to "$baseName-$assetVersion-$osArch"
        }
        val jvmZip = jvmDistZip?.archiveFile
        inputs.property("stripReleaseBinaries", eignexCli.stripReleaseBinaries)
        // macOS needs -x (non-global symbols only): a full strip fails on linked Mach-O executables.
        val stripCommand = if (HostManager.hostIsMac) listOf("strip", "-x") else listOf("strip")

        doLast {
            val dir = assetsDir.asFile
            dir.deleteRecursively()
            dir.mkdirs()
            val assets = mutableListOf<File>()
            for ((outputFile, assetName) in nativeAssets) {
                val asset = outputFile.copyTo(dir.resolve(assetName))
                asset.setExecutable(true)
                // Best effort: keep the unstripped binary if strip is unavailable.
                // Discard output: an unread pipe fills up and deadlocks waitFor.
                val stripBinaries = inputs.properties["stripReleaseBinaries"] as Boolean
                if (stripBinaries) {
                    runCatching {
                        ProcessBuilder(stripCommand + asset.absolutePath)
                            .redirectOutput(ProcessBuilder.Redirect.DISCARD)
                            .redirectError(ProcessBuilder.Redirect.DISCARD)
                            .start()
                            .waitFor()
                    }
                }
                assets += asset
            }
            jvmZip?.let { assets += it.get().asFile.copyTo(dir.resolve("$baseName-$assetVersion-jvm.zip")) }
            val digest = MessageDigest.getInstance("SHA-256")
            dir.resolve("SHA256SUMS").writeText(
                assets.joinToString("") { asset ->
                    val sum = digest.digest(asset.readBytes()).joinToString("") { "%02x".format(it) }
                    "$sum  ${asset.name}\n"
                }
            )
        }
    }
}
