package com.eignex

import org.gradle.testkit.runner.TaskOutcome
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File

/**
 * TestKit harness that materializes a Gradle project applying com.eignex.lint and asserts detekt
 * reports the expected finding. One test per rule we want to lock in, each asserting the whole
 * finding (position and rule), so a rule that fires for the wrong reason still fails.
 */
class LintPluginRulesTest {

    @Test
    fun `a fully qualified call is reported by detektMain`(@TempDir dir: File) {
        val probe = lintProbe(dir)
        probe.write(
            "src/main/kotlin/HasFqn.kt",
            """
            /** Builds a list. */
            public fun build(): List<String> = kotlin.collections.listOf("x")
            """.trimIndent() + "\n"
        )

        // UnnecessaryFullyQualifiedName needs type resolution, which only detektMain has.
        probe.assertDetektReports(
            task = "detektMain",
            at = "HasFqn.kt:2:36",
            rule = "UnnecessaryFullyQualifiedName"
        )
    }

    @Test
    fun `an undocumented public class is reported by detekt`(@TempDir dir: File) {
        val probe = lintProbe(dir)
        probe.write("src/main/kotlin/Undocumented.kt", "public class Undocumented\n")

        probe.assertDetektReports(
            task = "detekt",
            at = "Undocumented.kt:1:14",
            rule = "UndocumentedPublicClass"
        )
    }

    @Test
    fun `a KDoc sentence without terminating punctuation is reported by detekt`(@TempDir dir: File) {
        val probe = lintProbe(dir)
        probe.write(
            "src/main/kotlin/BadSentence.kt",
            """
            /** A KDoc without a terminating period */
            public class BadSentence
            """.trimIndent() + "\n"
        )

        probe.assertDetektReports(
            task = "detekt",
            at = "BadSentence.kt:1:4",
            rule = "EndOfSentenceFormat"
        )
    }

    @Test
    fun `a deprecated KDoc block tag is reported by detekt`(@TempDir dir: File) {
        val probe = lintProbe(dir)
        probe.write(
            "src/main/kotlin/UsesDeprecatedTag.kt",
            """
            /**
             * Uses the deprecated KDoc tag.
             *
             * @deprecated use something else.
             */
            public class UsesDeprecatedTag
            """.trimIndent() + "\n"
        )

        probe.assertDetektReports(
            task = "detekt",
            at = "UsesDeprecatedTag.kt:1:1",
            rule = "DeprecatedBlockTag"
        )
    }

    @Test
    fun `detekt regenerates its config when the configuration cache is reused after build is cleared`(
        @TempDir dir: File,
    ) {
        val probe = lintProbe(dir)
        // A clean source file: internal (no undocumented-public rules) and nothing for the
        // style/comment rules to fire on.
        probe.write("src/main/kotlin/Clean.kt", "internal class Clean\n")

        // First run stores the configuration cache and writes the generated detekt config.
        probe.build("detekt", "--configuration-cache")

        // Simulate a fresh CI runner that restored only the Gradle home: the project-local
        // configuration cache (.gradle/) survives, but build/ does not, and neither does the
        // generated config inside it.
        probe.file("build").deleteRecursively()

        // The reuse run skips configuration, so the config must be regenerated by a task.
        val result = probe.build("detekt", "--configuration-cache")

        assertTrue("Reusing configuration cache" in result.output) {
            "expected the second run to reuse the configuration cache, got:\n${result.output}"
        }
        result.assertOutcome(":writeEignexDetektConfig", TaskOutcome.SUCCESS)
        result.assertOutcome(":detekt", TaskOutcome.SUCCESS)
        assertTrue(probe.file("build/tmp/eignex-detekt.yml").isFile) {
            "expected the detekt config to be regenerated, got:\n${result.output}"
        }
    }

    @Test
    fun `the built-in Eignex config can be disabled`(@TempDir dir: File) {
        val probe = lintProbe(dir, "eignexLint { useEignexConfig.set(false) }")

        probe.build("writeEignexDetektConfig")

        assertTrue(probe.file("build/tmp/eignex-detekt.yml").readText().isEmpty())
    }

    @Test
    fun `lint tasks can be disabled`(@TempDir dir: File) {
        val result = lintProbe(dir, "eignexLint { enabled.set(false) }").build("detekt")

        result.assertOutcome(":detekt", TaskOutcome.SKIPPED)
    }

    /**
     * Fails [task] and asserts detekt reported [rule] at [at] (a `file:line:col` position).
     *
     * The finding's prose is deliberately not asserted: it is the detekt engine's wording and
     * changes on upgrades, whereas the position and rule id are what these tests lock in.
     */
    private fun GradleProbe.assertDetektReports(task: String, at: String, rule: String) {
        val result = buildAndFail(task)

        result.assertOutcome(":$task", TaskOutcome.FAILED)
        val reported = result.output.lineSequence().any { line ->
            val finding = line.trimEnd()
            "$at " in finding && finding.endsWith("[$rule]")
        }
        assertTrue(reported) { "expected detekt to report [$rule] at $at, got:\n${result.output}" }
    }
}
