package com.eignex

import org.gradle.testkit.runner.TaskOutcome
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File

/**
 * TestKit harness that materializes a Gradle project applying com.eignex.lint and asserts detekt
 * reports the expected finding. One test per rule we want to lock in, each asserting the whole
 * finding — position, message and rule — so a rule that fires for the wrong reason still fails.
 */
class LintPluginRulesTest {

    @Test
    fun `a fully qualified call is reported by detektMain`(@TempDir dir: File) {
        val probe = lintProbe(dir)
        probe.write(
            "src/main/kotlin/HasFqn.kt",
            """
            /** Builds a list. */
            public fun build(): List<String> = kotlin.collections.listOf("x")
            """.trimIndent() + "\n"
        )

        // UnnecessaryFullyQualifiedName needs type resolution, which only detektMain has.
        probe.assertDetektReports(
            task = "detektMain",
            finding = "HasFqn.kt:2:36 Fully qualified function call 'kotlin.collections.listOf' " +
                "can be replaced with an import. [UnnecessaryFullyQualifiedName]"
        )
    }

    @Test
    fun `an undocumented public class is reported by detekt`(@TempDir dir: File) {
        val probe = lintProbe(dir)
        probe.write("src/main/kotlin/Undocumented.kt", "public class Undocumented\n")

        probe.assertDetektReports(
            task = "detekt",
            finding = "Undocumented.kt:1:14 Undocumented is missing required documentation. " +
                "[UndocumentedPublicClass]"
        )
    }

    @Test
    fun `a KDoc sentence without terminating punctuation is reported by detekt`(@TempDir dir: File) {
        val probe = lintProbe(dir)
        probe.write(
            "src/main/kotlin/BadSentence.kt",
            """
            /** A KDoc without a terminating period */
            public class BadSentence
            """.trimIndent() + "\n"
        )

        probe.assertDetektReports(
            task = "detekt",
            finding = "BadSentence.kt:1:4 The first sentence of this KDoc does not end with the " +
                "correct punctuation. [EndOfSentenceFormat]"
        )
    }

    @Test
    fun `a deprecated KDoc block tag is reported by detekt`(@TempDir dir: File) {
        val probe = lintProbe(dir)
        probe.write(
            "src/main/kotlin/UsesDeprecatedTag.kt",
            """
            /**
             * Uses the deprecated KDoc tag.
             *
             * @deprecated use something else.
             */
            public class UsesDeprecatedTag
            """.trimIndent() + "\n"
        )

        probe.assertDetektReports(
            task = "detekt",
            finding = "UsesDeprecatedTag.kt:1:1 @deprecated tag block does not properly report " +
                "deprecation in Kotlin, use @Deprecated annotation instead [DeprecatedBlockTag]"
        )
    }

    @Test
    fun `detekt regenerates its config when the configuration cache is reused after build is cleared`(
        @TempDir dir: File,
    ) {
        val probe = lintProbe(dir)
        // A clean source file: internal (no undocumented-public rules) and nothing for the
        // style/comment rules to fire on.
        probe.write("src/main/kotlin/Clean.kt", "internal class Clean\n")

        // First run stores the configuration cache and writes the generated detekt config.
        probe.build("detekt", "--configuration-cache")

        // Simulate a fresh CI runner that restored only the Gradle home: the project-local
        // configuration cache (.gradle/) survives, but build/ — and the generated config in
        // it — does not.
        probe.file("build").deleteRecursively()

        // The reuse run skips configuration, so the config must be regenerated by a task.
        val result = probe.build("detekt", "--configuration-cache")

        assertTrue("Reusing configuration cache" in result.output) {
            "expected the second run to reuse the configuration cache, got:\n${result.output}"
        }
        result.assertOutcome(":writeEignexDetektConfig", TaskOutcome.SUCCESS)
        result.assertOutcome(":detekt", TaskOutcome.SUCCESS)
        assertTrue(probe.file("build/tmp/eignex-detekt.yml").isFile) {
            "expected the detekt config to be regenerated, got:\n${result.output}"
        }
    }

    /** Fails [task] and asserts detekt printed exactly [finding] (a `file:line:col … [Rule]` line). */
    private fun GradleProbe.assertDetektReports(task: String, finding: String) {
        val result = buildAndFail(task)

        result.assertOutcome(":$task", TaskOutcome.FAILED)
        assertTrue(result.output.lineSequence().any { it.trimEnd().endsWith(finding) }) {
            "expected detekt to report \"$finding\", got:\n${result.output}"
        }
    }
}
